# Generated by Django 4.2.25 on 2025-12-05 06:44

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "episode_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("episode_number", models.IntegerField()),
                ("episode_title", models.CharField(max_length=150)),
                ("schedule_start_ts", models.DateField()),
                ("schedule_end_ts", models.DateField()),
                ("total_viewers", models.IntegerField()),
                ("tech_interruption_flag", models.CharField(max_length=1)),
                ("duration_minutes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "language_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebSeries",
            fields=[
                (
                    "web_series_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("no_of_episodes", models.IntegerField()),
                ("language", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("description", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("schedule_start_ts", models.DateField()),
                ("schedule_end_ts", models.DateField()),
                ("is_live_flag", models.CharField(default="N", max_length=1)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.episode"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episode",
            name="web_series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "Customer"), ("employee", "Employee")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="WebSeriesDubbing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dubbing_studio", models.CharField(max_length=120, null=True)),
                ("dubbing_artist", models.CharField(max_length=120, null=True)),
                ("audio_quality", models.CharField(max_length=20, null=True)),
                ("release_date", models.DateField(null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.language"
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
            options={
                "unique_together": {("web_series", "language")},
            },
        ),
    ]
