# Generated by Django 4.2.25 on 2025-12-08 05:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "episode_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("episode_number", models.IntegerField()),
                ("episode_title", models.CharField(max_length=200)),
                ("schedule_start_ts", models.DateTimeField(blank=True, null=True)),
                ("schedule_end_ts", models.DateTimeField(blank=True, null=True)),
                ("total_viewers", models.IntegerField(default=0)),
                (
                    "tech_interruption_flag",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
                    ),
                ),
                ("duration_minutes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "language_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "producer_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("producer_name", models.CharField(max_length=120)),
                ("email_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=80, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionHouse",
            fields=[
                (
                    "production_house_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("prod_house_name", models.CharField(max_length=100, unique=True)),
                ("street", models.CharField(blank=True, max_length=120, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=80, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("year_established", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeriesType",
            fields=[
                (
                    "series_type_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebSeries",
            fields=[
                (
                    "web_series_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("no_of_episodes", models.IntegerField()),
                ("release_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.language",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.producer",
                    ),
                ),
                (
                    "producer_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productionhouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewerAccount",
            fields=[
                (
                    "account_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("street", models.CharField(blank=True, max_length=120, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=80, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "monthly_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("plan_type", models.CharField(max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.vieweraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("schedule_start_ts", models.DateTimeField()),
                ("schedule_end_ts", models.DateTimeField()),
                (
                    "is_live_flag",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.episode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_text",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("feedback_date", models.DateField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.vieweraccount",
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episode",
            name="web_series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "contract_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField()),
                (
                    "per_episode_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_contract_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("contract_status", models.CharField(max_length=20)),
                (
                    "prod_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productionhouse",
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "Customer"), ("employee", "Employee")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="WebSeriesType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seriestype",
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
            options={
                "unique_together": {("web_series", "series_type")},
            },
        ),
        migrations.CreateModel(
            name="WebSeriesSubtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.language"
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
            options={
                "unique_together": {("web_series", "language")},
            },
        ),
        migrations.CreateModel(
            name="WebSeriesDubbing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dubbing_studio",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "dubbing_artist",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "audio_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.language"
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
            options={
                "unique_together": {("web_series", "language")},
            },
        ),
        migrations.CreateModel(
            name="WebSeriesCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "web_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webseries"
                    ),
                ),
            ],
            options={
                "unique_together": {("web_series", "country")},
            },
        ),
        migrations.CreateModel(
            name="ProducerHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producer"
                    ),
                ),
                (
                    "production_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionhouse",
                    ),
                ),
            ],
            options={
                "unique_together": {("producer", "production_house")},
            },
        ),
    ]
